language: java 

jdk:
    - oraclejdk8

notifications:
  email:
    recipients:
      - peter0930260535@gmail.com
    on_success: always
    on_failure: always

sudo: false

cahce:
    directories:
        - $HOME/.m2

script:
    mvn clean test 
